services:
  runner:
    build:
      context: .
      dockerfile: sample-ci/docker/test/Dockerfile
    command: ['tail', '-f', '/dev/null']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SERVER_URL=http://web:4242
      - BUNDLE_JOBS=5

  stripe:
    image: stripe/stripe-cli:v1.5.3
    entrypoint: ['/bin/ash']
    command: ['-c', '/bin/stripe --api-key=$STRIPE_SECRET_KEY listen --forward-to http://web:4242/stripe-webhook']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  web:
    build:
      context: .
      dockerfile: sample-ci/docker/${SERVER_LANG}/Dockerfile
      args:
        sample: ${SAMPLE}
    ports: ['4242:4242']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STATIC_DIR=${STATIC_DIR}
