services:
  runner:
    image: ruby:2.7.1
    working_dir: /work
    entrypoint: ['/work/sample-ci/docker/runner/entrypoint.sh']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SERVER_URL=http://web:4242
      - BUNDLE_JOBS=5
    volumes:
      - work:/work

  stripe:
    image: stripe/stripe-cli:v1.5.3
    entrypoint: ['/bin/ash']
    command: ['-c', '/bin/stripe --api-key=$STRIPE_SECRET_KEY listen --forward-to http://web:4242/webhook']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  web:
    build:
      context: .
      dockerfile: sample-ci/docker/${SERVER_TYPE}/Dockerfile
    working_dir: /work/${SAMPLE}/server/${SERVER_TYPE}
    entrypoint: ['/work/sample-ci/docker/${SERVER_TYPE}/entrypoint.sh']
    ports: ['4242:4242']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STATIC_DIR=${STATIC_DIR}
    volumes:
      - work:/work

volumes:
  work:
